# 一 numpy数组
numpy 提供了一种数组类型(高维数组),提供了数据分析的运算基础

In [1]:
import numpy as np
np.__version__

'1.21.5'

In [ ]:
# C: 数组的概念, 用于存储一系列相同数据类型,在内存上是连续的一段空间
# Python: 列表(list):从C看,是一种指针数组,列表中可以存储不同数据类型的元素

In [ ]:
# Numpy的数组,同样是一个[有序]的,[相同数据类型]的集合

In [ ]:
# numpy设计初衷是用于运算的,所以对数据类型进行统一优化
# 注意:
#     numpy默认ndarray的所有元素的类型是相同的
#     如果传进来的列表中包含不同的类型,则统一为同一类型,优先级:str>float>int

In [3]:
arr = np.array([1,1.23,"hello"])

In [4]:
arr

array(['1', '1.23', 'hello'], dtype='<U32')

In [7]:
int_lst = [1,2,3,4,5,6]
arr_int = np.array(int_lst)
arr_int


array([1, 2, 3, 4, 5, 6])

In [7]:
import numpy as np
int_lst = [1,2,3,4,5,6]
arr_int = np.array(int_lst,dtype=np.float32) # 使用dtype更改或标注数据类型
arr_int

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [10]:
# 创建二维数组,使用shape
import numpy as np
# 1.np.ones(shape,dtype=None,order='C') 创建shape的单位数组
# shape = (m,n) m row,n column 二维数组
# shape = (m)   m row          一维数组
# shape = (m,)  m row          一维数组
# shape = (m,1)  m row  1 column   二维数组
# shape = (1,n)  1 row  n column   二维数组
arr1 = np.ones((3,2),dtype=None,order='C') #创建3行2列的单位数组
arr1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# 2.np.zeros(shape,dtype=None,order='C') 创建shape的0数组
arr2 = np.zeros((2,3,4),dtype=int,order='C') # 2个3行4列的3维数组
arr2

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [13]:
# 3. np.full(shape,fill_value,dtype=None,order='C') 创建shape的指定value的数组
arr3 = np.full((4,5),5,dtype=None,order='C')
arr3

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
# 4. np.eye(N,M=None,k=0,dtype=None) N阶单位矩阵;M控制列数,一般不用;k移动对角线位置;
arr4 = np.eye(3,M=None,k=1,dtype=None)
arr4

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [20]:
# 5.np.linspace(start,end,num=50,endpoint=True,restep=False,dtype=None) 创建等差数列
# num 数列的个数; endpoint 包含Endpoint否
arr5 = np.linspace(1,10,num=10,dtype=None)
arr5

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
# 6.np.arange([start, ]stop, step, dtype) 创建等差数列, 关注步长
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 7.np.random.randint(low,high=None,size=None,dtype='l') 随机整数 ,size同shape
np.random.randint(0,100,size=(5,5))

array([[22, 66, 39,  5, 87],
       [ 2, 51, 43, 43, 24],
       [94, 11, 65,  1, 27],
       [94, 99, 48, 69, 97],
       [ 7, 92, 53, 29, 93]])

In [30]:
# 8.正态分布函数
# np.random.randn(d0,d1,,,,dn)#标准正态分布
# np.random.randn(3,5) 
# np.random.normal(d0,d1,,,,dn) # 普通正态分布.
np.random.normal(loc=170,scale=5,size=(5,5)) #

array([[171.43689203, 169.58109492, 169.04676603, 175.57263296,
        163.8422358 ],
       [171.64076829, 165.92532783, 177.64639919, 166.95739195,
        179.1088858 ],
       [170.10295944, 178.51206664, 173.70429346, 172.65498474,
        168.89062323],
       [159.27495728, 170.95005576, 171.65372176, 165.57904169,
        166.68001965],
       [164.82764667, 164.86544172, 163.08402819, 168.53391498,
        159.51665307]])

In [33]:
# 9.  0~1的随机数
np.random.random(100)
np.random.random(size=(5,5))

array([[0.85047301, 0.63107922, 0.53818214, 0.26605571, 0.84663913],
       [0.4935123 , 0.67791257, 0.48427225, 0.38593424, 0.26849556],
       [0.44233906, 0.29818756, 0.28542177, 0.51115514, 0.41339527],
       [0.72715667, 0.60620312, 0.31139643, 0.1252117 , 0.68694081],
       [0.42218121, 0.5141423 , 0.78371882, 0.43929419, 0.8209172 ]])

In [34]:
np.random.permutation(10) # 0~10的随机索引

array([7, 9, 8, 2, 1, 3, 4, 0, 6, 5])

# 二、ndarray的属性
4个必记参数:
    ·ndim:维度
    ·shape:形状(各维度的长度)
    ·size:总长度
    ·dtype:元素类型
    
arr.ndim
arr.shape
arr.size
arr.dtype

# 三、ndarray的基本操作

In [ ]:
#1. 索引
一维数组与列表完全一致, 多维同理

In [35]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[5]

6

In [40]:
arr = np.array([[0,1,2,3,4,],
               [5,6,7,8,9]])
arr[0][1]# 第0行第1列

1

In [41]:
arr = np.array([[0,1,2,3,4,],
               [5,6,7,8,9]])
arr[0,1]# 第0行第1列

1