# 4 Pandas

## 4.1 介绍

pandas = panel + data + analysis


### 4.1.1 为什么使用Pandas
1. 便捷的数据处理能力
2. 读取文件方便
3. 封装了matplotlib,numpy的画图与计算


### 4.1.2 DataFrame
  1. 结构: 既有行索引,也有列索引的二维数组  
  2. 属性: shape          index          columns          values          T  
  3. 方法: head(), tail()  
  4. 索引的设置  
      4.1 修改行列索引的值  
      4.2 重设索引  
      4.3 设置新索引  


In [1]:
import numpy as np 
#创建一个符合正态分布的10个股票5天的涨跌幅数据
stock_change = np.random.normal(0,1,(10,5))
stock_change

array([[ 1.02167505,  2.72608272,  0.90274974,  1.15893729,  1.21278641],
       [-1.75636629, -1.65175647, -1.13136059,  0.47635033, -1.2054201 ],
       [-0.4976545 ,  0.78234542, -1.15826083, -1.06183147, -1.25295089],
       [ 0.20057076, -0.05305768, -1.22866922, -1.2377074 ,  1.50972497],
       [ 0.12388692, -1.54353717,  1.01887692, -1.82784302, -0.14810419],
       [ 1.30380296, -0.0458388 , -0.83008252, -0.08078966,  0.62076211],
       [-0.77735786, -1.43261913,  0.79211327,  0.00364723,  1.43698149],
       [-0.13059062, -0.47076236,  1.00866195, -0.02841271, -1.1771119 ],
       [-0.58959685,  0.34550373, -0.26728295,  0.34478202, -0.56077798],
       [ 0.69175521, -0.1539802 ,  0.02051458, -0.1962341 ,  0.34747971]])

In [2]:
import pandas as pd 
pd.DataFrame(stock_change)

0         1         2         3         4
0  1.021675  2.726083  0.902750  1.158937  1.212786
1 -1.756366 -1.651756 -1.131361  0.476350 -1.205420
2 -0.497655  0.782345 -1.158261 -1.061831 -1.252951
3  0.200571 -0.053058 -1.228669 -1.237707  1.509725
4  0.123887 -1.543537  1.018877 -1.827843 -0.148104
5  1.303803 -0.045839 -0.830083 -0.080790  0.620762
6 -0.777358 -1.432619  0.792113  0.003647  1.436981
7 -0.130591 -0.470762  1.008662 -0.028413 -1.177112
8 -0.589597  0.345504 -0.267283  0.344782 -0.560778
9  0.691755 -0.153980  0.020515 -0.196234  0.347480

In [3]:
# 添加行索引
stock = [f"股票{i+1}" for i in range(10)]
stock


['股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9', '股票10']

In [4]:
# 添加列索引
date = pd.date_range(start="20180101",periods=5,freq="B")
date

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='B')

In [5]:
import pandas as pd 
data = pd.DataFrame(stock_change,index=stock,columns=date)

In [6]:
# 2 属性
print(data.shape)
print("*"*30)
print(data.index)
print("*"*30)
print(data.columns)
print("*"*30)
print(data.values)
# print(data.T)

(10, 5)
******************************
Index(['股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9', '股票10'], dtype='object')
******************************
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='B')
******************************
[[ 1.02167505  2.72608272  0.90274974  1.15893729  1.21278641]
 [-1.75636629 -1.65175647 -1.13136059  0.47635033 -1.2054201 ]
 [-0.4976545   0.78234542 -1.15826083 -1.06183147 -1.25295089]
 [ 0.20057076 -0.05305768 -1.22866922 -1.2377074   1.50972497]
 [ 0.12388692 -1.54353717  1.01887692 -1.82784302 -0.14810419]
 [ 1.30380296 -0.0458388  -0.83008252 -0.08078966  0.62076211]
 [-0.77735786 -1.43261913  0.79211327  0.00364723  1.43698149]
 [-0.13059062 -0.47076236  1.00866195 -0.02841271 -1.1771119 ]
 [-0.58959685  0.34550373 -0.26728295  0.34478202 -0.56077798]
 [ 0.69175521 -0.1539802   0.02051458 -0.1962341   0.34747971]]


In [7]:
# 3 方法
print(data.head(2))
print("*"*30)
print(data.tail(3))

     2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05
股票1    1.021675    2.726083    0.902750    1.158937    1.212786
股票2   -1.756366   -1.651756   -1.131361    0.476350   -1.205420
******************************
      2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05
股票8    -0.130591   -0.470762    1.008662   -0.028413   -1.177112
股票9    -0.589597    0.345504   -0.267283    0.344782   -0.560778
股票10    0.691755   -0.153980    0.020515   -0.196234    0.347480


####  索引的设置  

In [8]:
# 4.1 修改行列索引的值 
print(data.index[2]) 
# data.index[2] = "股票3" # 不能单独修改某个索引
stock_ = [f"股票_{i+1}" for i in range(10)]
print(stock_)
data = pd.DataFrame(stock_change,index=stock_,columns=date)
data

股票3
['股票_1', '股票_2', '股票_3', '股票_4', '股票_5', '股票_6', '股票_7', '股票_8', '股票_9', '股票_10']


2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05
股票_1     1.021675    2.726083    0.902750    1.158937    1.212786
股票_2    -1.756366   -1.651756   -1.131361    0.476350   -1.205420
股票_3    -0.497655    0.782345   -1.158261   -1.061831   -1.252951
股票_4     0.200571   -0.053058   -1.228669   -1.237707    1.509725
股票_5     0.123887   -1.543537    1.018877   -1.827843   -0.148104
股票_6     1.303803   -0.045839   -0.830083   -0.080790    0.620762
股票_7    -0.777358   -1.432619    0.792113    0.003647    1.436981
股票_8    -0.130591   -0.470762    1.008662   -0.028413   -1.177112
股票_9    -0.589597    0.345504   -0.267283    0.344782   -0.560778
股票_10    0.691755   -0.153980    0.020515   -0.196234    0.347480

In [9]:
 
# 4.2 重设索引   # 用处不多
# reset_index(drop=False)
# 设置新的下标索引
# drop:默认为False,不删除原来索引,如果为True,删除原来的索引值

data.reset_index()

index  2018-01-01 00:00:00  2018-01-02 00:00:00  2018-01-03 00:00:00  \
0   股票_1             1.021675             2.726083             0.902750   
1   股票_2            -1.756366            -1.651756            -1.131361   
2   股票_3            -0.497655             0.782345            -1.158261   
3   股票_4             0.200571            -0.053058            -1.228669   
4   股票_5             0.123887            -1.543537             1.018877   
5   股票_6             1.303803            -0.045839            -0.830083   
6   股票_7            -0.777358            -1.432619             0.792113   
7   股票_8            -0.130591            -0.470762             1.008662   
8   股票_9            -0.589597             0.345504            -0.267283   
9  股票_10             0.691755            -0.153980             0.020515   

   2018-01-04 00:00:00  2018-01-05 00:00:00  
0             1.158937             1.212786  
1             0.476350            -1.205420  
2            -1.061831            -1.252951  
3            -1.237707             1.509725  
4            -1.827843            -0.148104  
5            -0.080790             0.620762  
6             0.003647             1.436981  
7            -0.028413            -1.177112  
8             0.344782            -0.560778  
9            -0.196234             0.347480

In [10]:
import pandas as pd
# .以某列值设置为新的索引
#   set_index(keys,drop=True)
# ·keys:列索引名成或者列索引名称的列表
# ·drop:boolean,default True.当做新的索引,删除原来的列


# 4.3 设置新索引 
df = pd.DataFrame({'month':[1,4,7,10],
                    'year':[2012,2014,2013,2014],
                    'sale':[55,40,84,31]})

In [11]:
df

month  year  sale
0      1  2012    55
1      4  2014    40
2      7  2013    84
3     10  2014    31

In [12]:
#以月份设置新的索引
df.set_index("month",drop=False)

month  year  sale
month                   
1          1  2012    55
4          4  2014    40
7          7  2013    84
10        10  2014    31

In [13]:
df.set_index("month")

year  sale
month            
1      2012    55
4      2014    40
7      2013    84
10     2014    31

In [14]:
# 设置多个索引 以年和月份
new_df = df.set_index(["year","month"]) #注:通过设置,DataFram就变成了一个具有Multilndex的DataFrame.

print(new_df.index)

new_df

MultiIndex([(2012,  1),
            (2014,  4),
            (2013,  7),
            (2014, 10)],
           names=['year', 'month'])


sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

### 4.1.3 MultiIndex 与Panel


#### 1. MultiIndex

In [15]:

# index 属性: 
#     names: levels的名称
#     levels:每个level的元组值
new_df.index.names

FrozenList(['year', 'month'])

In [16]:
new_df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

#### 2. Panel (已弃用)

In [17]:
import numpy as np
import pandas as pd
p = pd.Panel(np.array(24).reshape(4,3,2),
             items=list['ABCD'],
             major_axis=pd.data_range('20130101',periods=3),
             minor_axis=['first','second'])
p

AttributeError: module 'pandas' has no attribute 'Panel'

### 4.1.4 Series  
    带索引的一维数组.  
    只有行索引

属性: index, values  
方法: 

In [ ]:
data


2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05
股票_1     1.285282    0.904201   -2.095527   -2.209579    0.069798
股票_2    -0.471220   -1.374783    0.094551    0.325409    0.304745
股票_3     2.787400   -1.500788    1.691239   -0.583304   -0.155487
股票_4    -0.727471   -0.418444    0.137762    0.487916    1.015779
股票_5    -1.521013   -0.522335   -0.199272    0.499149    0.274449
股票_6     0.432487   -0.389577   -1.581655   -0.442407   -0.501114
股票_7     1.624606    2.902537    0.703359    1.497414   -0.671857
股票_8     0.539920    1.145140    0.322813   -0.822948    0.292674
股票_9    -1.727199    0.469651    0.601913    0.445923   -0.513953
股票_10    0.557170   -0.330087    0.599816    1.400115   -1.275658

In [ ]:
sr = data.iloc[1,:]

In [ ]:
print(sr.index)
print(sr.values)
print(type(sr.index))
print(type(sr.values))

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='B')
[-0.47122017 -1.37478322  0.09455136  0.3254089   0.30474456]
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
<class 'numpy.ndarray'>


#### 1. 创建Series 
通过已有数据创建   
    * 指定内容,默认索引  
    * 指定索引  
通过字典数据创建  

In [ ]:
import numpy as np
import pandas as pd
pd.Series(np.arange(3,9,2)) #* 指定内容,默认索引

0    3
1    5
2    7
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
pd.Series(np.arange(3,9,2),index=['a','b','c']) #* 指定索引  

a    3
b    5
c    7
dtype: int64

总结:  
    DataFrame是Series的容器  
    Panel是DataFrame的容器

## 4.2 基本数据操作

 4.2.1索引操作  
    1 直接索引  (必须先列后行)  
        data['行索引名字']['列索引名字']   
    2 按名字索引  
        data.loc['行索引名字']['列索引名字']  
        data.loc['行索引名字','列索引名字']  
    3 按数字索引  
        data.iloc[1,0]  
    4 组合索引(数字,名字混用)   # 可能未来被弃用
        data.ix[0:4,['A','B']]
 4.2.2赋值操作  
    #直接修改原来的值
        data['close'] = 1
    #或者
        data.close = 1

 4.2.3排序 
    对内容排序
     DataFrame  
        ·使用df.sort_values(by='a',key=,ascending=)对单个字段的内容进行排序
            .单个键或者多个键进行排序,默认升序
                ascending=False:降序 
                ascending=True:升序
        ·多个字段排序df.sort_values(by=['a','b'],ascending=True)
     Series
        sr=data['a'].sort_values(ascending=True)
    对索引排序
     DataFrame 
        data.sort_index() 
     Series  
        sr.sort_values(ascending=True)
 4.2.4总结  

## 4.3 DataFrame 运算

### 4.3.1 算术运算


In [ ]:
data["A"].add(3) # Series:对某列加3
data + 10 # DataFrame 每个加10
data.sub(10) # DataFrame 每个减10

### 4.3.2 逻辑运算  
1. 逻辑运算符 < > | &
2. 逻辑运算函数 query(), isin()



In [ ]:
data['p_change'] > 2 # 返回带索引的布尔值
data[data['p_change'] > 2] # 筛选 p_change>2 的DataFrame

In [ ]:
# query(expression) 更方便
data.query("p_change > 2 & turnover > 15")

In [ ]:
# isin(values)
# 判断'turnover'是否为4.19,2.39, 并筛选
data[data['turnover'].isin([4.19,2.39])]

### 4.3.3 统计运算  
min max mean median var  std ...

In [ ]:
# 1 describe()
# 综合分析:能够直接得出很多统计结果,count,mean,std,min,max等
# 计算平均值、标准差、最大值、最小值
data.describe()

#2 统计函数
data.max(axis=0) # 默认按列(axis=0), 列(axis=1)求最大值
data.idxmax()    # 最大值所在索引

# 累计统计函数
# cumsum(),cummax(),cummin(),cumprod() 前n个数据的和,最大/最小值,乘
data['p_change'].sort_index().cumsum().plot() # 

### 4.3.4 自定义运算

In [ ]:
apply(func,axis=0)
    ·func:自定义函数
    ·axis=0:默认是列,axis=1 为行进行运算
定义一个对列,最大值-最小值的函数
data.apply(lambda x : x.max()-x.min())

## 4.4 Pandas画图

In [ ]:
# sr.plot()
# dataframe.plot(x=None,y=None,kind='line')
x label or position,default None
y:label,position or list of label,positions,default None
    Allows plotting of one column versus anothero 
kind: str
    'line':line plot (default)
    'bar':vertical bar plot
    'barh':horizontal bar plot
    'hist':histogram
    'pie':pie plot
    'scatter':scatter plot


In [ ]:
data.plot(x="p_change",y="turnover",kind="scatter")

## 4.5 文件读取与存储

## 4.6 高级处理-缺失值处理

## 4.7 高级处理-数据离散化

## 4.8 高级处理-合并

## 4.9 高级处理-交叉表与透视表

## 4.10 高级处理-分组与聚合

## 4.11 综合案例