In [10]:
import collections
Card = collections.namedtuple('Card', ['rank', 'suit'])
class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()
    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits
                                        for rank in self.ranks]
    def __len__(self):
        return len(self._cards)
    def __getitem__(self, position):
        return self._cards[position]


In [52]:
beer_card = Card('7', 'diamonds')
type(beer_card)


__main__.Card

In [20]:
deck = FrenchDeck()
len(deck)  #52
# deck[0]  #Card(rank='2', suit='spades')
# deck[-1] #Card(rank='A', suit='hearts')

52

In [26]:
from random import choice
choice(deck)  #choice() missing 1 required positional argument: 'seq'

Card(rank='A', suit='hearts')

In [31]:
deck[:3]

[Card(rank='2', suit='spades'),
 Card(rank='3', suit='spades'),
 Card(rank='4', suit='spades')]

In [32]:
deck[2:3]

[Card(rank='4', suit='spades')]

In [34]:
for card in reversed(deck):
    print(card)

Card(rank='A', suit='hearts')
Card(rank='K', suit='hearts')
Card(rank='Q', suit='hearts')
Card(rank='J', suit='hearts')
Card(rank='10', suit='hearts')
Card(rank='9', suit='hearts')
Card(rank='8', suit='hearts')
Card(rank='7', suit='hearts')
Card(rank='6', suit='hearts')
Card(rank='5', suit='hearts')
Card(rank='4', suit='hearts')
Card(rank='3', suit='hearts')
Card(rank='2', suit='hearts')
Card(rank='A', suit='clubs')
Card(rank='K', suit='clubs')
Card(rank='Q', suit='clubs')
Card(rank='J', suit='clubs')
Card(rank='10', suit='clubs')
Card(rank='9', suit='clubs')
Card(rank='8', suit='clubs')
Card(rank='7', suit='clubs')
Card(rank='6', suit='clubs')
Card(rank='5', suit='clubs')
Card(rank='4', suit='clubs')
Card(rank='3', suit='clubs')
Card(rank='2', suit='clubs')
Card(rank='A', suit='diamonds')
Card(rank='K', suit='diamonds')
Card(rank='Q', suit='diamonds')
Card(rank='J', suit='diamonds')
Card(rank='10', suit='diamonds')
Card(rank='9', suit='diamonds')
Card(rank='8', suit='diamonds')
Card(r

In [75]:
suit_values = dict(spades=3, hearts=2, diamonds=1, clubs=0)
def spades_high(card):
    print("inside:",card)
    # print("card.rank:",card.rank)
    # print("card.suit:",card.suit)
    rank_value = FrenchDeck.ranks.index(card.rank)
    print("rank_value:",rank_value)
    print("len(suit_values):",len(suit_values))
    print("suit_values[card.suit]:",suit_values[card.suit])
    print("rerurn:",rank_value * len(suit_values) + suit_values[card.suit])
    print(15*"*")
    return rank_value * len(suit_values) + suit_values[card.suit]

In [76]:

for card in sorted(deck, key=spades_high): # doctest: +ELLIPSIS
    print("outside:",card)
    # break

inside: Card(rank='2', suit='spades')
rank_value: 0
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 3
***************
inside: Card(rank='3', suit='spades')
rank_value: 1
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 7
***************
inside: Card(rank='4', suit='spades')
rank_value: 2
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 11
***************
inside: Card(rank='5', suit='spades')
rank_value: 3
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 15
***************
inside: Card(rank='6', suit='spades')
rank_value: 4
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 19
***************
inside: Card(rank='7', suit='spades')
rank_value: 5
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 23
***************
inside: Card(rank='8', suit='spades')
rank_value: 6
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 27
***************
inside: Card(rank='9', suit='spades')
rank_value: 7
len(suit_values): 4
suit_values[card.suit]: 3
rerurn: 31
***************
in

In [79]:
from math import hypot
class Vector:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
    def __repr__(self):
        return 'Vector(%r, %r)' % (self.x, self.y)
    def __abs__(self):
        return hypot(self.x, self.y)
    def __bool__(self):
        return bool(abs(self))
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        return Vector(x, y)
    def __mul__(self, scalar):
        return Vector(self.x * scalar, self.y * scalar)

In [80]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt)


black S
black M
black L
white S
white M
white L


In [81]:
metro_areas = [
    ('Tokyo','JP',36.933,(35.689722,139.691667)), # ➊
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
    ]
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (latitude, longitude) in metro_areas: # ➋
    if longitude <= 0: # ➌
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [92]:
# 定义和使用具名元组
from collections import namedtuple

##创建一个具名元组需要两个参数， 一个是类名， 另一个是类的各个字段的名字。 后者可以是由数个字符串组成的可迭代对象，或者是由空格分隔开的字段名组成的字符串。
City = namedtuple('City', 'name country population coordinates')  

tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
# print(tokyo )
# print(tokyo.name)
# print(tokyo.country)
# print(tokyo.population)
# print(tokyo.coordinates)
# print(City._fields)


LatLong = namedtuple('LatLong', 'lat long')
print("LatLong: ",type(LatLong))

delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
print("delhi_data: ",delhi_data)
# _make() 通过接受一个可迭代对象来生成这个类的一个实例， 它的作用跟 City(*delhi_data) 是一样的。
delhi = City._make(delhi_data)

#_asdict() 把具名元组以 collections.OrderedDict 的形式返回， 我们可以利用它来把元组里的信息友好地呈现出来。
delhi._asdict() 
print("delhi._asdict() :",delhi._asdict() )

for key, value in delhi._asdict().items():
    print(key + ':', value)

LatLong:  <class 'type'>
delhi_data:  ('Delhi NCR', 'IN', 21.935, LatLong(lat=28.613889, long=77.208889))
delhi._asdict() : {'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613889, long=77.208889)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


In [99]:
l = list(range(10))
print(l)

l[2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l[3::2] = [11, 22]
print(l)

#如果赋值的对象是一个切片， 那么赋值语句的右侧必须是个可迭代对象。 即便只有单独一个值， 也要把它转换成可迭代的序列
l[2:5] = [100]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]
[0, 1, 100, 22, 9]


In [105]:
board = [['_'] * 3 for i in range(3)]
print(board)
board[1][2] = 'X'
print(board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]


In [106]:
weird_board = [['_'] * 3] * 3 
print(weird_board)
weird_board[1][2] = 'O'  #一旦我们试图标记第 1 行第 2 列的元素，就立马暴露了列表内的 3个引用指向同一个对象的事实。
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [110]:
l = [1, 2, 3]
print(id(l))
l *= 2
print(id(l))

print("_"*20)
t = (1, 2, 3)
print(id(t))
t *= 2
print(id(t))


2522263189824
2522263189824
____________________
2522263986304
2522263890144


In [113]:
t = (1, 2, [30, 40])
t[2] += [50, 60]
t

TypeError: 'tuple' object does not support item assignment

In [129]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]
ROW_FMT = '{0:2d} @ {1:2d}:    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle) 
        print("needle:", needle)
        print("position: ",position)
        offset = position * '  |' 
        print(ROW_FMT.format(needle, position, offset))
        print("-"*80)
    
if __name__ == '__main__':
    # if sys.argv[-1] == 'left':
    #     bisect_fn = bisect.bisect_left
    # else:
    #     bisect_fn = bisect.bisect
    bisect_fn = bisect.bisect
    # print("bisect_fn",bisect_fn)
    # print('DEMO:', bisect_fn.__name__) 
    # print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)   
    

needle: 31
position:  14
31 @ 14:      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
--------------------------------------------------------------------------------
needle: 30
position:  14
30 @ 14:      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
--------------------------------------------------------------------------------
needle: 29
position:  13
29 @ 13:      |  |  |  |  |  |  |  |  |  |  |  |  |29
--------------------------------------------------------------------------------
needle: 23
position:  11
23 @ 11:      |  |  |  |  |  |  |  |  |  |  |23
--------------------------------------------------------------------------------
needle: 22
position:  9
22 @  9:      |  |  |  |  |  |  |  |  |22
--------------------------------------------------------------------------------
needle: 10
position:  5
10 @  5:      |  |  |  |  |10
--------------------------------------------------------------------------------
needle: 8
position:  5
 8 @  5:      |  |  |  |  |8 
-------------------------

In [130]:
import bisect

def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]
[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [131]:
import bisect
import random
SIZE=7
random.seed(1729)
my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [140]:
import numpy
a = numpy.arange(12)
print(a)
print(type(a))
print(a.shape)
a.shape = 3, 4
print(a)
print(a[2])
print(a[2, 1])#打印第 2 行第 1 列的元素
print(a[:, 1] )#把第 1 列打印出来
print(a.transpose() )#行和列交换

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# 示例 2-23 使用双向队列

In [149]:
from collections import deque


#maxlen 是一个可选参数， 代表这个队列可以容纳的元素的数量, 一旦设定， 这个属性就不能修改了。
dq = deque(range(10), maxlen=10)
print(dq)

# 队列的旋转操作接受一个参数 n， 当 n > 0 时， 队列的最右边的 n 个元素会被移动到队列的左边。 当 n < 0 时， 最左边的 n 个元素会被移动到右边。
dq.rotate(3) 
print(dq)

dq.rotate(-4)
print(dq)

#当试图对一个已满（len(d) == d.maxlen） 的队列做尾部添加操作的时候， 它头部的元素会被删除掉。 注意在下一行里， 元素 0 被删除了
dq.appendleft(-1)
print(dq)

#在尾部添加 3 个元素的操作会挤掉 -1、 1 和 2。
dq.extend([11, 22, 33])
print(dq)

#extendleft(iter) 方法会把迭代器里的元素逐个添加到双向队列的左边， 因此迭代器里的元素会逆序出现在队列里。
dq.extendleft([10, 20, 30, 40])
print(dq)


deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)


In [150]:
__builtins__.__dict__

{'__name__': 'builtins',
 '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.",
 '__package__': '',
 '__loader__': _frozen_importlib.BuiltinImporter,
 '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
 '__build_class__': <function __build_class__>,
 '__import__': <function __import__>,
 'abs': <function abs(x, /)>,
 'all': <function all(iterable, /)>,
 'any': <function any(iterable, /)>,
 'ascii': <function ascii(obj, /)>,
 'bin': <function bin(number, /)>,
 'breakpoint': <function breakpoint>,
 'callable': <function callable(obj, /)>,
 'chr': <function chr(i, /)>,
 'compile': <function compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, *, _feature_version=-1)>,
 'delattr': <function delattr(obj, name, /)>,
 'dir': <function dir>,
 'divmod': <function divmod(x, y, /)>,
 'eval': <function eval(source, globals=None, 

In [ ]:
import collections

class StrKeyDict(collections.UserDict):
    def __missing__(self, key):
        if isinstance(key, str): #如果找不到的键本身就是字符串， 那就抛出 KeyError 异常。
            raise KeyError(key)
        return self[str(key)]    #如果找不到的键不是字符串， 那么把它转换成字符串再进行查找
    
    def __contains__(self, key):
        return str(key) in self.data
    
    def __setitem__(self, key, item): #把所有的键都转换成字符串。 把具体的实现委托给了 self.data 属性
        self.data[str(key)] = item
    



In [151]:
from dis import dis
dis('{1}') 

  1           0 LOAD_CONST               0 (1)
              2 BUILD_SET                1
              4 RETURN_VALUE


In [152]:
from dis import dis
dis('set([1])') 

  1           0 LOAD_NAME                0 (set)
              2 LOAD_CONST               0 (1)
              4 BUILD_LIST               1
              6 CALL_FUNCTION            1
              8 RETURN_VALUE


# 示例 4-1 编码和解码

In [156]:
s = 'café'
print(len(s))
b = s.encode('utf-8')#使用 UTF-8 把 str 对象编码成 bytes 对象。
print(b)
print(len(b))
U+FFFD REPLACEMENT CHARACTERprint(b.decode('utf-8')) #使用 UTF-8 把 b 对象解码成 str 对象

4
b'caf\xc3\xa9'
5
café


In [40]:
s = 'U+FFFDU+FFFD'.encode('utf-8')
print(s.decode('GBK'))
s2 = b'\xef\xbf\xbd\xef\xbf\xbd'
print(s2.decode('GBK'))





U+FFFDU+FFFD
锟斤拷


In [188]:
cafe = bytes('café', encoding='utf_8') # bytes 对象可以从 str 对象使用给定的编码构建
print(cafe)
print(cafe[0],cafe[1],cafe[2],cafe[3],cafe[4])

print(cafe[:1]) # 字节码为b'c'
print(cafe[:1].decode('utf-8'))

cafe_arr = bytearray(cafe)
print(cafe_arr)
print(cafe_arr[-2:] )

b'caf\xc3\xa9'
99 97 102 195 169
b'c'
c
bytearray(b'caf\xc3\xa9')
bytearray(b'\xc3\xa9')


In [227]:
import array
numbers = array.array('h',[-2,-1,0,1,2])
print(numbers)
octets = bytes(numbers)

print(octets)
# print(octets.decode('utf-8'))

array('h', [-2, -1, 0, 1, 2])
b'\xfe\xff\xff\xff\x00\x00\x01\x00\x02\x00'


In [229]:
for codec in ['latin_1', 'utf_8', 'utf_16']:
    print(codec, 'El Niño'.encode(codec), sep='\t\t')

latin_1		b'El Ni\xf1o'
utf_8		b'El Ni\xc3\xb1o'
utf_16		b'\xff\xfeE\x00l\x00 \x00N\x00i\x00\xf1\x00o\x00'


In [233]:
## 示例 4-6 编码成字节序列： 成功和错误处理
city = 'São Paulo'
print(city.encode('utf_8') )
print(city.encode('utf_16'))
print(city.encode('iso8859_1') )
print("-"*20)
print(city.encode('cp437', errors='ignore')) #跳过无法编码的字符； 这样做通常很是不妥
print(city.encode('cp437', errors='replace'))  #无法编码的字符替换成 '?'
print(city.encode('cp437', errors='xmlcharrefreplace')) #把无法编码的字符替换成 XML实体



b'S\xc3\xa3o Paulo'
b'\xff\xfeS\x00\xe3\x00o\x00 \x00P\x00a\x00u\x00l\x00o\x00'
b'S\xe3o Paulo'
--------------------
b'So Paulo'
b'S?o Paulo'
b'S&#227;o Paulo'


In [234]:
# 示例 4-7 把字节序列解码成字符串： 成功和错误处理
octets = b'Montr\xe9al'
print(octets.decode('cp1252') )
print(octets.decode('iso8859_7'))
print(octets.decode('koi8_r'))
# print(octets.decode('utf_8'))
print(octets.decode('utf_8', errors='replace') ) #使用 'replace' 错误处理方式， \xe9 替换成了“ �”

Montréal
Montrιal
MontrИal
Montr�al


In [11]:
from unicodedata import normalize
s1 = 'café' # 把"e"和重音符组合在一起
s2 = 'cafe\u0301' # 分解成"e"和重音符
print(len(s1), len(s2))

print(len(normalize('NFC', s1)), len(normalize('NFC', s2)))

print(len(normalize('NFD', s1)), len(normalize('NFD', s2)))

print(normalize('NFC', s1) == normalize('NFC', s2))
print(normalize('NFD', s1) == normalize('NFD', s2))

4 5
4 4
5 5
True
True


In [14]:
from unicodedata import normalize, name
half = '½'
print(normalize('NFKC', half))

four_squared = '4²'
print(normalize('NFKC', four_squared))

micro = 'μ'
micro_kc = normalize('NFKC', micro)


print(ord(micro), ord(micro_kc))

print(name(micro), name(micro_kc))

1⁄2
42
956 956
GREEK SMALL LETTER MU GREEK SMALL LETTER MU


In [17]:
import unicodedata
import string

def shave_marks(txt):
    """去掉全部变音符号"""
    norm_txt = unicodedata.normalize('NFD', txt)  #把所有字符分解成基字符和组合记号
    print(norm_txt)
    shaved = ''.join(c for c in norm_txt if not unicodedata.combining(c)) # 过滤掉所有组合记号
    print(shaved)
    return unicodedata.normalize('NFC', shaved) 

order = '“Herr Voß: • ½ cup of OEtker™ caffè latte • bowl of açaí.”'
shave_marks(order)

“Herr Voß: • ½ cup of OEtker™ caffè latte • bowl of açaí.”
“Herr Voß: • ½ cup of OEtker™ caffe latte • bowl of acai.”


'“Herr Voß: • ½ cup of OEtker™ caffe latte • bowl of acai.”'

In [41]:
fruits = ['strawberry', 'fig', 'apple', 'cherry', 'raspberry', 'banana']

sorted(fruits, key=len)

['fig', 'apple', 'cherry', 'banana', 'raspberry', 'strawberry']

In [52]:
def reverse(word):
    return word[::-1] #反转字符串，步长必须是负值
# reverse('testing')

fruits = ['strawberry', 'fig', 'apple', 'cherry', 'raspberry', 'banana']
sorted(fruits, key=reverse)

['banana', 'apple', 'fig', 'raspberry', 'strawberry', 'cherry']

In [50]:
#示例 5-7 使用 lambda 表达式反转拼写， 然后依此给单词列表排序
fruits = ['strawberry', 'fig', 'apple', 'cherry', 'raspberry', 'banana']
sorted(fruits, key=lambda word: word[::-1])


['banana', 'apple', 'fig', 'raspberry', 'strawberry', 'cherry']

In [64]:
#调用 BingoCage 实例， 从打乱的列表中取出一个元素

import random

class BingoCage:

    def __init__(self, items):
        self._items = list(items) 
        random.shuffle(self._items) #random.shuffle()用于将一个列表中的元素打乱顺序


    def pick(self): 
        try:
            return self._items.pop()
        except IndexError:
            raise LookupError('pick from empty BingoCage') 
        
    def __call__(self): 
        return self.pick()


bingo = BingoCage(range(3))
bingo.pick()
bingo()



0

In [72]:
def tag(name, *content, cls=None, **attrs):
    print(name, content, cls, attrs)
    """生成一个或多个HTML标签"""
    if cls is not None:
        attrs['class'] = cls
        
    if attrs:
        attr_str = ''.join(' %s="%s"' % (attr, value)  for attr, value in sorted(attrs.items()))
    else:
        attr_str = ''
        
    if content:
        return '\n'.join('<%s%s>%s</%s>' % (name, attr_str, c, name) for c in content)
    else:
        return '<%s%s />' % (name, attr_str)
    
    
tag('br')
tag('p', 'hello')
print(tag('p', 'hello', 'world'))
tag('p', 'hello', id=33)
print(tag('p', 'hello', 'world', cls='sidebar'))

br () None {}
p ('hello',) None {}
p ('hello', 'world') None {}
<p>hello</p>
<p>world</p>
p ('hello',) None {'id': 33}
p ('hello', 'world') sidebar {}
<p class="sidebar">hello</p>
<p class="sidebar">world</p>


In [2]:
registry = [] 
def register(func): 
    print('running register(%s)' % func) 
    registry.append(func) 
    return func 

@register 
def f1():
    print('running f1()')
    
@register
def f2():
    print('running f2()')
    
def f3(): 
    print('running f3()')


def main(): 
    print('running main()')
    print('registry ->', registry)
    f1()
    f2()
    f3()
if __name__=='__main__':
    main()

running register(<function f1 at 0x000002EA9ED30AF0>)
running register(<function f2 at 0x000002EA9ED30C10>)
running main()
registry -> [<function f1 at 0x000002EA9ED30AF0>, <function f2 at 0x000002EA9ED30C10>]
running f1()
running f2()
running f3()


In [6]:
from dis import dis
b = 6
def f1(a):
    print(a)
    print(b)
    
# f1(3)
dis(f1)

  4           0 LOAD_GLOBAL              0 (print)
              2 LOAD_FAST                0 (a)
              4 CALL_FUNCTION            1
              6 POP_TOP

  5           8 LOAD_GLOBAL              0 (print)
             10 LOAD_GLOBAL              1 (b)
             12 CALL_FUNCTION            1
             14 POP_TOP
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


In [7]:
from dis import dis
b = 6
def f2(a):
    print(a)
    print(b)
    b = 9

dis(f2)

  4           0 LOAD_GLOBAL              0 (print)
              2 LOAD_FAST                0 (a)
              4 CALL_FUNCTION            1
              6 POP_TOP

  5           8 LOAD_GLOBAL              0 (print)
             10 LOAD_FAST                1 (b)
             12 CALL_FUNCTION            1
             14 POP_TOP

  6          16 LOAD_CONST               1 (9)
             18 STORE_FAST               1 (b)
             20 LOAD_CONST               0 (None)
             22 RETURN_VALUE


In [ ]:
def make_averager():
    series = []
    def averager(new_value):
        series.append(new_value)
        total = sum(series)
        return total/len(series)
    return averager

avg = make_averager()
avg(10)

In [12]:
import time
import functools

# def clock(func):
#     def clocked(*args): # ➊定义内部函数 clocked， 它接受任意个位置参数
#         t0 = time.perf_counter()
#         result = func(*args) # ➋ 这行代码可用， 是因为 clocked 的闭包中包含自由变量 func。
#         elapsed = time.perf_counter() - t0
#         name = func.__name__
#         arg_str = ', '.join(repr(arg) for arg in args)
#         print('[%0.8fs] %s(%s) -> %r' % (elapsed, name, arg_str, result))
#         return result
#     return clocked # ➌返回内部函数， 取代被装饰的函数


def clock(func):
    @functools.wraps(func)
    def clocked(*args, **kwargs):
        t0 = time.time()
        result = func(*args, **kwargs)
        elapsed = time.time() - t0
        name = func.__name__
        arg_lst = []
        if args:
            arg_lst.append(', '.join(repr(arg) for arg in args))
        if kwargs:
            pairs = ['%s=%r' % (k, w) for k, w in sorted(kwargs.items())] 
            arg_lst.append(', '.join(pairs))
        arg_str = ', '.join(arg_lst)
        print('[%0.8fs] %s(%s) -> %r ' % (elapsed, name, arg_str, result))
        return result
    return clocked



@clock
def snooze(seconds):
    time.sleep(seconds)
    
@clock
def factorial(n):
    return 1 if n < 2 else n*factorial(n-1)


snooze(.123)
factorial(6)
# print('6! =', factorial(6))


[0.12835073s] snooze(0.123) -> None 
[0.00000000s] factorial(1) -> 1 
[0.00000000s] factorial(2) -> 2 
[0.00000000s] factorial(3) -> 6 
[0.00000000s] factorial(4) -> 24 
[0.00000000s] factorial(5) -> 120 
[0.00000000s] factorial(6) -> 720 


720

In [19]:
class Gizmo:
    def __init__(self):
        print('Gizmo id: %d' % id(self))

x = Gizmo()

# y = Gizmo() * 10

# dir()

Gizmo id: 3206713267104


In [29]:
charles = {'name': 'Charles L. Dodgson', 'born': 1832, 'balance': 950}

lewis = charles
print(lewis == charles)
print(lewis is charles)

print(id(charles), id(lewis))
print("-"*40)
alex = {'name': 'Charles L. Dodgson', 'born': 1832, 'balance': 950} 

print(alex == charles) # 比较的是值
print(alex is charles) # 比较的是内存地址
print(id(charles), id(alex)) # id() 获取内存地址,在对象的生命周期中绝不会变



True
True
3206724090048 3206724090048
----------------------------------------
True
False
3206724090048 3206721915904


In [39]:
# 元组的相对不可变性

t1 = (1, 2, [30, 40])
t2 = (1, 2, [30, 40])
print(t1 == t2)
print(id(t1), id(t2))
print(id(t1[-1]))
print("after add element to list")
t1[-1].append(99)
print(t1)
print(id(t1[-1]) )
print(t1 == t2)
print(id(t1), id(t2))

True
3206723856512 3206723996480
3206723732736
after add element to list
(1, 2, [30, 40, 99])
3206723732736
False
3206723856512 3206723996480


In [41]:
# 默认做浅复制

l1 = [3, [55, 44], (7, 8, 9)]
l2 = list(l1)

print(l2 == l1 )
print(l2 is l1)



True
False


In [44]:
# 为任意对象做深复制和浅复制
import copy
class Bus:
    def __init__(self, passengers=None):
        if passengers is None:
            self.passengers = []
        else:
            self.passengers = list(passengers)
            
    def pick(self, name):
        self.passengers.append(name)
        
    def drop(self, name):
        self.passengers.remove(name)


bus1 = Bus(['Alice', 'Bill', 'Claire', 'David'])
bus2 = copy.copy(bus1) # 浅拷贝
bus3 = copy.deepcopy(bus1) # 深拷贝
print( id(bus1), id(bus2), id(bus3)) # 3206711452624 3206711452336 3206711451904 ID不同
bus1.drop('Bill')
print(bus2.passengers)
print(id(bus1.passengers), id(bus2.passengers), id(bus3.passengers)) #3206723723072 3206723723072 3206723700672 前两个ID相同

print(bus3.passengers)

3206711187200 3206713432240 3206711435072
['Alice', 'Claire', 'David']
3206723695488 3206723695488 3206724163840
['Alice', 'Bill', 'Claire', 'David']


In [46]:
from copy import deepcopy
a = [10, 20]
b = [a, 30]
a.append(b)
print(a)
c = deepcopy(a)
print(c)


[10, 20, [[...], 30]]
[10, 20, [[...], 30]]


In [52]:
class TwilightBus:
    """让乘客销声匿迹的校车"""
    def __init__(self, passengers=None):
        if passengers is None:
            self.passengers = [] #当 passengers 为 None 时， 创建一个新的空列表
        else:
            self.passengers = passengers # self.passengers 变成 passengers 的别名， 而后者是传给 __init__ 方法的实参
        print('id of passengers:',id(passengers))
    def pick(self, name):
        self.passengers.append(name)
    def drop(self, name):
        self.passengers.remove(name) #在 self.passengers 上调用 .remove() 和 .append() 方法其实会修改传给构造方法的那个列表

basketball_team = ['Sue', 'Tina', 'Maya', 'Diana', 'Pat']
print('id of basketball_team:',id(basketball_team))
bus = TwilightBus(basketball_team)
bus.drop('Tina')
bus.drop('Pat')
print(basketball_team) #下车的学生从篮球队中消失了！





id of basketball_team: 3206723653696
id of passengers: 3206723653696
['Sue', 'Maya', 'Diana']


In [53]:
# 上面的问题是， 校车为传给构造方法的列表创建了别名。 正确的做法是， 校车自己维护乘客列表。 修正的方法很简单： 在 __init__ 中， 传
# 入 passengers 参数时， 应该把参数值的副本赋值给self.passengers，

"""
在内部像这样处理乘客列表， 就不会影响初始化校车时传入的参数了。
此外， 这种处理方式还更灵活： 现在， 传给 passengers 参数的值可以
是元组或任何其他可迭代对象
"""
class TwilightBus:
    """让乘客销声匿迹的校车"""
    def __init__(self, passengers=None):
        if passengers is None:
            self.passengers = [] #当 passengers 为 None 时， 创建一个新的空列表
        else:
            # self.passengers = passengers
            self.passengers = list(passengers)  #创建 passengers 列表的副本； 如果不是列表， 就把它转换成列表
        print('id of passengers:',id(passengers))
        print('id of self.passengers:',id(self.passengers))
    def pick(self, name):
        self.passengers.append(name)
    def drop(self, name):
        self.passengers.remove(name)

basketball_team = ['Sue', 'Tina', 'Maya', 'Diana', 'Pat']
print('id of basketball_team:',id(basketball_team))
bus = TwilightBus(basketball_team)
bus.drop('Tina')
bus.drop('Pat')
print(basketball_team) #下车的学生没有从篮球队中消失

id of basketball_team: 3206723683072
id of passengers: 3206723683072
id of self.passengers: 3206710459456
['Sue', 'Tina', 'Maya', 'Diana', 'Pat']


In [64]:
# 正是因为有引用， 对象才会在内存中存在。 当对象的引用数量归零后，
# 垃圾回收程序会把对象销毁。 但是， 有时需要引用对象， 而不让对象存
# 在的时间超过所需时间。 这经常用在缓存中。

"""弱引用不会增加对象的引用数量。 引用的目标对象称为所指对象
（referent） 。 因此我们说， 弱引用不会妨碍所指对象被当作垃圾回收。"""

import weakref
a_set = {0, 1}
print('id of a_set',hex(id(a_set)).upper())
wref = weakref.ref(a_set)  #创建弱引用对象 wref

print(wref)
print(wref())
a_set = {2, 3, 4} # a_set 不再指代 {0, 1} 集合， 因此集合的引用数量减少了。 但是 变量仍然指代它。
print(wref)
wref() is None


id of a_set 0X2EA9FA01580
<weakref at 0x000002EA9ED6A680; to 'set' at 0x000002EA9FA01580>
{0, 1}
<weakref at 0x000002EA9ED6A680; dead>


True

In [82]:
from array import array
import math
class Vector2d:
    typecode = 'd'  #typecode 是类属性， 在 Vector2d 实例和字节序列之间转换时使用。
    def __init__(self, x, y): # x,y 实例属性
        self.x = float(x) #在 __init__ 方法中把 x 和 y 转换成浮点数， 尽早捕获错误， 以防调用 Vector2d 函数时传入不当参数
        self.y = float(y)
        print(self)
        
    def __iter__(self):
        """定义 __iter__ 方法， 把 Vector2d 实例变成可迭代的对象， 这样才
            能拆包(例如， x, y = my_vector) 。 这个方法的实现方式很简单，
            直接调用生成器表达式一个接一个产出分量。"""
        return (i for i in (self.x, self.y)) 
    
    def __repr__(self):
        """__repr__ 方法使用 {!r} 获取各个分量的表示形式， 然后插值， 构
        成一个字符串； 因为 Vector2d 实例是可迭代的对象， 所以 *self 会把
        x 和 y 分量提供给 format 函数。"""
        class_name = type(self).__name__
        return '{}({!r}, {!r})'.format(class_name, *self) 
    
    def __str__(self):
        return str(tuple(self)) #从可迭代的 Vector2d 实例中可以轻松地得到一个元组， 显示为一个有序对
    
    def __bytes__(self):
        """ord() 函数是以一个字符(长度为1的字符串)作为参数,返回对应的 ASCII 数值，或者 Unicode 数值，如果所给的 Unicode 字符超出了你的 Python 定义范围，则会引发一个 TypeError 的异常。"""
        return (bytes([ord(self.typecode)]) + bytes(array(self.typecode, self))) 
    
    def __eq__(self, other):
        return tuple(self) == tuple(other) 
    
    def __abs__(self):
        return math.hypot(self.x, self.y) 
    
    def __bool__(self):
        return bool(abs(self))
    
    def __format__(self, fmt_spec=''):
        if fmt_spec.endswith('p'): 
            fmt_spec = fmt_spec[:-1] 
            coords = (abs(self), self.angle()) 
            outer_fmt = '<{}, {}>' 
        else:
            coords = self 
            outer_fmt = '({}, {})' 
        components = (format(c, fmt_spec) for c in coords) 
        return outer_fmt.format(*components)
    
    @classmethod  #类方法使用 classmethod 装饰器修饰。
    def frombytes(cls, octets): #不用传入 self 参数； 相反， 要通过 cls 传入类本身。
        typecode = chr(octets[0]) #从第一个字节中读取 typecode。
        memv = memoryview(octets[1:]).cast(typecode) #使用传入的 octets 字节序列创建一个 memoryview， 然后使用typecode 转换
        return cls(*memv) #拆包转换后的 memoryview， 得到构造方法所需的一对参数

v1 = Vector2d(3, 4)
print("1.",v1.x, v1.y)
x, y = v1     #Vector2d 实例可以拆包成变量元组。
print("2.",x, y)

# v1
print("3.",repr(v1))
v1_clone = eval(repr(v1))  # 等价于 v1_clone = Vector2d(3.0, 4.0)
print("4.",v1 == v1_clone)
print("5.",v1) #print 函数会调用 str 函数,对 Vector2d 来说， 输出的是一个有序对。
octets = bytes(v1) #bytes 函数会调用 __bytes__ 方法， 生成实例的二进制表示形式。 b'd\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@'

print("6.",octets)
print("7.",abs(v1)) #abs 函数会调用 __abs__ 方法， 返回 Vector2d 实例的模。
print("8.",bool(v1), bool(Vector2d(0, 0)) ) #bool 函数会调用 __bool__ 方法， 如果 Vector2d 实例的模为零，返回 False， 否则返回 True。





(3.0, 4.0)
1. 3.0 4.0
2. 3.0 4.0
3. Vector2d(3.0, 4.0)
(3.0, 4.0)
4. True
5. (3.0, 4.0)
6. b'd\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@'
7. 5.0
(0.0, 0.0)
8. True False


In [5]:
dic = {'a': 2, 'b': 8, 'c': 5, 'd': 9}
ans = max(dic, key=dic.get) # get() 函数返回指定键的值。
ans


'd'

In [5]:
# 创建一个字典
my_dict = {'a': 1, 'c': 3, 'b': 2, 'd': 4}

# 使用max()函数获取字典中最大值对应的键
max_key = max(my_dict, key=lambda item: my_dict[item])

# 输出结果
print("The key with the maximum value is:", max_key)


The key with the maximum value is: d


In [3]:
class Fibs:
    def __init__(self):
        self.a = 0
        self.b = 1
    def __next__(self):
        self.a, self.b = self.b, self.a + self.b
        return self.a
    def __iter__(self):
        return self

fibs = Fibs()
for i in fibs:
    print(i,end=' ')
    if i >100:
        break

1 1 2 3 5 8 13 21 34 55 89 144 

In [7]:
nested = [[1, 2], [3, 4], [5]]

def flatten(nested):
    for sublist in nested:
        for element in sublist:
            yield element

for i in flatten(nested):
    print(i)
list(flatten(nested))

1
2
3
4
5


[1, 2, 3, 4, 5]

In [10]:
def swap(m,n):
    print("in ",m,n,id(m),id(n))
    tmp = m
    m = n
    n = tmp
    print("in ",tmp,id(tmp))
    print("in ",m,n,id(m),id(n))

a = 10
b = 20
print("out",a,b,id(a),id(b))
swap(a,b)
print("out",a,b,id(a),id(b))

out 10 20 2613152148048 2613152148368
in  10 20 2613152148048 2613152148368
in  10 2613152148048
in  20 10 2613152148368 2613152148048
out 10 20 2613152148048 2613152148368


In [3]:
from pyecharts import options as opts
from pyecharts.charts import Bar
from pyecharts.faker import Faker
# print(Faker.values())

c = (
    Bar()
    .add_xaxis(Faker.choose())
    .add_yaxis("商家A", Faker.values())
    .add_yaxis("商家B", Faker.values())
    .set_global_opts(title_opts=opts.TitleOpts(title="Bar-基本示例", subtitle="我是副标题"))
    .render("bar_base.html")
)


In [ ]:
import  json
aa = {'dns': {'servers': [{'tag': 'proxyDns', 'address': 'https://8.8.8.8/dns-query', 'detour': 'proxy'}, {'tag': 'localDns', 'address': 'https://223.5.5.5/dns-query', 'detour': 'direct'}, {'tag': 'block', 'address': 'rcode://success'}], 'rules': [{'domain': ['ghproxy.com', 'cdn.jsdelivr.net', 'testingcf.jsdelivr.net'], 'server': 'localDns'}, {'rule_set': 'geosite-category-ads-all', 'server': 'block'}, {'outbound': 'any', 'server': 'localDns', 'disable_cache': True}, {'rule_set': 'geosite-cn', 'server': 'localDns'}, {'clash_mode': 'direct', 'server': 'localDns'}, {'clash_mode': 'global', 'server': 'proxyDns'}, {'rule_set': 'geosite-geolocation-!cn', 'server': 'proxyDns'}], 'strategy': 'ipv4_only'},}
# print(json.dumps(aa, indent=4))


In [2]:
import os
import sys
print(sys.platform)

win32
